/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) *   FROM [FABS].[dbo].[countries]
SELECT TOP (1000) *   FROM [FABS].[dbo].[zipcode_country_city]
SELECT TOP (1000) *   FROM [FABS].[dbo].[addresses]
SELECT TOP (1000) *   FROM [FABS].[dbo].[organisations]
SELECT TOP (1000) *   FROM [FABS].[dbo].[organisation_person]
SELECT TOP (1000) *   FROM [FABS].[dbo].[people]
SELECT TOP (1000) *   FROM [FABS].[dbo].[logins]
SELECT TOP (1000) *   FROM [FABS].[dbo].[statuses]
SELECT TOP (1000) *   FROM [FABS].[dbo].[items]
SELECT TOP (1000) *   FROM [FABS].[dbo].[item_types]
SELECT TOP (1000) *   FROM [FABS].[dbo].[kayak_types]
SELECT TOP (1000) *   FROM [FABS].[dbo].[locations]
SELECT TOP (1000) *   FROM [FABS].[dbo].[warehouses]
SELECT TOP (1000) *   FROM [FABS].[dbo].[booking_line]
SELECT TOP (1000) *   FROM [FABS].[dbo].[bookings]